# Generated by Django 4.1.1 on 2022-11-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_imageformmodel_main_imageformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_imageformmodel',
        ),
    ]
